frase = 'Curso em Vídeo Python'
print(frase)
print(frase.upper().count('O'))
print(frase[3:13])
print(frase[:13])
print(frase[13:])
print(frase[1:15:2])
print(frase[::2])
print(len(frase))
print(frase.replace('Python', 'Android'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(frase.split())
print('-'.join(frase))
print(len(frase.strip()))
frase = frase.replace('Python', 'Android')
print(frase)
print('Curso' in frase)
print(frase.lower().find('vídeo'))
dividido = frase.split()
print(dividido[2][3])

frase_2 = '   Aprenda Python   '
print(frase_2.strip())
print(frase_2.rstrip())
print(frase_2.lstrip())
print(len(frase_2))